### ISSUE TITLE
Crash during lint

### ISSUE THREAD

**Issue by 4censord** [ansible-community/ansible-lint#1751] opened 2021-10-21 12:30 UTC
##### Summary

Ansible-lint crashes with `KeyError: 0 ` while trying to lint the following ansible task file:
```yaml
---
# tasks file for influxdb
- name: Installation
  import_tasks:
    file: "{{item}}"
    apply:
      tags: influxdb.install
      notify: restart influxdb
  with_first_found:
    - "install-{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"
    - "install-{{ ansible_distribution }}.yml"
    - "install-{{ ansible_os_family }}.yml"
  tags:
    - influxdb.install
```

##### Issue Type

- Bug Report

##### Ansible and Ansible Lint details

This happens both with latest main `60f2205` and the version in the Archlinux repos
###### From main
```console
ansible --version
ansible [core 2.11.6] 
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/daniel/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /tmp/ansible-lint/.venv/lib/python3.9/site-packages/ansible
  ansible collection location = /home/daniel/.ansible/collections:/usr/share/ansible/collections
  executable location = /tmp/ansible-lint/.venv/bin/ansible
  python version = 3.9.7 (default, Oct 10 2021, 15:13:22) [GCC 11.1.0]
  jinja version = 3.0.2
  libyaml = True

ansible-lint --version
ansible-lint 5.2.1 using ansible 2.11.6
```
###### From repos
```console
ansible [core 2.11.6] 
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/daniel/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.9/site-packages/ansible
  ansible collection location = /home/daniel/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.9.7 (default, Oct 10 2021, 15:13:22) [GCC 11.1.0]
  jinja version = 3.0.2
  libyaml = True

ansible-lint --version
ansible-lint 5.2.1 using ansible 2.11.6
```

- ansible installation method: source, OS package
- ansible-lint installation method: source,  OS package

##### OS / ENVIRONMENT

This is on arch linux, with nothing special i know of

##### STEPS TO REPRODUCE

* Create a file with this content called `main.yml`
```yaml
---
# tasks file for influxdb
- name: Installation
  import_tasks:
    file: "{{item}}"
    apply:
      tags: influxdb.install
      notify: restart influxdb
  with_first_found:
    - "install-{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"
    - "install-{{ ansible_distribution }}.yml"
    - "install-{{ ansible_os_family }}.yml"
  tags:
    - influxdb.install
```
* `ansible-lint main.yml`

##### Desired Behaviour

No crash, but a error message, along the lines of what ansible gives
`ERROR! Invalid options for import_tasks: apply`

##### Actual Behaviour

```console
0
Loading custom .yamllint config file, this extends our internal yamllint config.
Traceback (most recent call last):
  File "/tmp/ansible-lint/.venv/bin/ansible-lint", line 8, in <module>
    sys.exit(_run_cli_entrypoint())
  File "/tmp/ansible-lint/.venv/lib/python3.9/site-packages/ansiblelint/__main__.py", line 299, in _run_cli_entrypoint
    sys.exit(main(sys.argv))
  File "/tmp/ansible-lint/.venv/lib/python3.9/site-packages/ansiblelint/__main__.py", line 236, in main
    result = _get_matches(rules, options)
  File "/tmp/ansible-lint/.venv/lib/python3.9/site-packages/ansiblelint/runner.py", line 201, in _get_matches
    matches.extend(runner.run())
  File "/tmp/ansible-lint/.venv/lib/python3.9/site-packages/ansiblelint/runner.py", line 136, in run
    matches.extend(self._emit_matches(files))
  File "/tmp/ansible-lint/.venv/lib/python3.9/site-packages/ansiblelint/runner.py", line 169, in _emit_matches
    for child in ansiblelint.utils.find_children(lintable):
  File "/tmp/ansible-lint/.venv/lib/python3.9/site-packages/ansiblelint/utils.py", line 255, in find_children
    for child in play_children(basedir, item, lintable.kind, playbook_dir):
  File "/tmp/ansible-lint/.venv/lib/python3.9/site-packages/ansiblelint/utils.py", line 328, in play_children
    return delegate_map[k](basedir, k, v, parent_type)
  File "/tmp/ansible-lint/.venv/lib/python3.9/site-packages/ansiblelint/utils.py", line 344, in _include_children
    result = path_dwim(os.path.join(os.path.dirname(basedir)), v)
  File "/tmp/ansible-lint/.venv/lib/python3.9/site-packages/ansiblelint/utils.py", line 102, in path_dwim
    return str(dl.path_dwim(given))
  File "/tmp/ansible-lint/.venv/lib/python3.9/site-packages/ansible/parsing/dataloader.py", line 186, in path_dwim
    given = unquote(given)
  File "/tmp/ansible-lint/.venv/lib/python3.9/site-packages/ansible/parsing/quoting.py", line 29, in unquote
    if is_quoted(data):
  File "/tmp/ansible-lint/.venv/lib/python3.9/site-packages/ansible/parsing/quoting.py", line 24, in is_quoted
    return len(data) > 1 and data[0] == data[-1] and data[0] in ('"', "'") and data[-2] != '\\'
KeyError: 0
```

**Comment by 4censord** [comment] 2021-10-21 13:11
It doesn't seem to crash with simply the file.
i didn't test with the file isolated in a fresh directory.

It seem to only crash while there is a .yamllint config file present, like the one generated by `molecule init role test`

In a new folder `test/` with only 
```console
tree -a
.
├── .yamllint
└── tasks
    └── main.yml
```
It crashes.
In the same directory, but with `main.yml` moved on layer up
```console
.
├── .yamllint
├── main.yml
└── tasks
```
it does not crash.
.yamllint, generated by molecule 
```
molecule 3.5.2 using python 3.9 
    ansible:2.11.6
    delegated:3.5.2 from molecule
    docker:1.0.2 from molecule_docker requiring collections: community.docker>=1.8.0
    podman:1.0.1 from molecule_podman requiring collections: containers.podman>=1.7.0 ansible.posix>=1.3.0
    vagrant:0.2 from molecule_vagrant
```
```yaml
---
# Based on ansible-lint config
extends: default

rules:
  braces:
    max-spaces-inside: 1
    level: error
  brackets:
    max-spaces-inside: 1
    level: error
  colons:
    max-spaces-after: -1
    level: error
  commas:
    max-spaces-after: -1
    level: error
  comments: disable
  comments-indentation: disable
  document-start: disable
  empty-lines:
    max: 3
    level: error
  hyphens:
    level: error
  indentation: disable
  key-duplicates: enable
  line-length: disable
  new-line-at-end-of-file: disable
  new-lines:
    type: unix
  trailing-spaces: disable
  truthy: disable
```

**Comment by ssbarnea** [comment] 2022-01-10 14:05
Closing as unable to reproduce. If someone can create a repository where running ansible lint does crash with this bug, I will be more than happy to reopen it.

**Closed by ssbarnea** 2022-01-10 14:05 UTC
Labels: bug
